server:
  port: 5601
  context-path: /academico

spring:
  application:
    name: academico
    profiles: docker
  datasource:
    url: jdbc:mysql://localhost:8889/olimpo
    username: sitecode
    password: sitecode

  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
    hibernate:
      ddl-auto: none
eureka:
  instance:
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2
    #ip-address: 192.168.0.16
    #hostname: 192.168.0.16
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      #defaultZone: http://192.168.0.16:1111/eureka/
      defaultZone: http://localhost:1111/eureka/