server:
  port: ${port:5602}
  context-path: /v1

spring:
  application:
    name: datacenter
    profiles: docker
  datasource:
    url: jdbc:mysql://${url.db:localhost:8889/olimpo}
    username: ${url.db.username:sitecode}
    password: ${url.db.password:sitecode}

  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
    hibernate:
      ddl-auto: none
eureka:
  instance:
    ip-address: ${ipaddress:192.168.0.16}
    hostname: ${hostname:172.16.7.115}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${url.registry:http://registry:1111/eureka/}
