server:
  port: 5602
  context-path: /datacenter

spring:
  application:
    name: datacenter
    profiles: docker
  datasource:
    url: jdbc:mysql://172.16.7.115:8889/olimpo
    username: root
    password: root

  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
    hibernate:
      ddl-auto: none
