server:
  port: ${port:5602}
  context-path: /v1

spring:
  application:
    name: datacenter
    profiles: docker
  datasource:
    url: jdbc:mysql://${url.db:localhost:3306/olimpo}
    driver-class-name: com.mysql.jdbc.Driver
    username: ${url.db.username:root}
    password: ${url.db.password:root}

  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: true

liquibase:
  change-log: classpath:dbchangelog.xml
  enabled: true

eureka:
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
    ip-address: ${ipaddress:localhost}
    hostname: ${hostname:localhost}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${url.registry:http://registry:1111/eureka/}
