eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false

server:
  port: ${port:1111}

spring:
  application:
    name: eureka
  thymeleaf:
    enabled: false
