server:
  port: 5600
  context-path: /v1

spring:
  application:
    name: seguridad
    profiles: docker
  datasource:
    url: jdbc:mysql://localhost:3306/olimpo
    username: sitecode
    password: sitecode

  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
    hibernate:
      ddl-auto: none
eureka:
  instance:
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2
    ip-address: 52.27.137.28
    hostname: 52.27.137.28
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://52.27.137.28:1111/eureka/
