server:
  port: 5600
  context-path: /seguridad

spring:
  application:
    name: seguridad
    profiles: docker
  datasource:
    #url: jdbc:mysql://192.168.0.16:8889/olimpo
    url: jdbc:mysql://172.16.7.115:8889/olimpo
    username: sitecode
    password: sitecode

  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
    hibernate:
      ddl-auto: none
eureka:
  instance:
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2
    #prefer-ip-address: true
    ip-address: 172.16.7.115
    hostname: 172.16.7.115
    homePageUrl: http://172.16.7.115:5600/
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      #defaultZone: http://192.168.0.16:1111/eureka/
      defaultZone: http://172.16.7.115:1111/eureka/