server:
  port: ${port:5600}
  context-path: /v1

spring:
  application:
    name: seguridad
    profiles: docker
  datasource:
    url: jdbc:mysql://${url.db:localhost:3306/olimpo}
    username: ${url.db.username:sitecode}
    password: ${url.db.password:sitecode}

  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
    hibernate:
      ddl-auto: none
eureka:
  instance:
    ip-address: ${ipaddress:52.27.137.28}
    hostname: ${hostname:52.27.137.28}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${url.registry:http://registry:1111/eureka/}
